[features]
seeds = false
skip-lint = false
[programs.localnet]
ve_nft = "HRsZWKJF1h4xuPwEyu5dxtH5EXkziqhWBr8esmGERCGs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/psd/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
